# data dumps
input_df_path: "data/raw/heart.csv"
output_model_path: "models/model.pkl"
output_transformer_path: "models/transformer.pkl"
metric_path: "models/metrics.json"
# features
categorical_features:
  - "sex"
  - "cp"
  - "fbs"
  - "restecg"
  - "exang"
  - "slope"
  - "ca"
  - "thal"
numerical_features:
  - "age"
  - "trestbps"
  - "chol"
  - "thalach"
  - "oldpeak"
target_col: "target"
# splitting
val_size: 0.2
random_state: 69
# models
defaults:
  - model: lr