apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: online-inference-replicaset
  labels:
    app: online-inference
spec:
  replicas: 2
  selector:
    matchLabels:
      app: online-inference
  template:
    metadata:
      name: online-inference-replicaset
      labels:
        app: online-inference
    spec:
      containers:
        - image: munraito/online_inference:v3
          name: online-inference
          ports:
            - containerPort: 8000